# Spring config properties
spring.config.import=optional:file:.env[.properties]

spring.application.name=holycrud
spring.datasource.url=jdbc:postgresql://localhost:${POST_PORT}/${POST_DB}
spring.datasource.username=${POST_USER}
spring.datasource.password=${POST_PASSWORD}
